# Generated by Django 5.0.7 on 2024-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_images_product_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='shortdis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
